### ISSUE TITLE
API lacks support for retrieving station list checksum 

### ISSUE THREAD

**Issue by jcass77** [mcrute/pydora#4]
At the moment, ```get_station_list()``` discards the ```checksum``` field when retrieving the list of stations from Pandora.

This, combined with the fact that ```user.getStationListChecksum``` has not been implemented yet means that it is not possible to cache a local copy of the station list without risking it becoming stale.

I'm not sure how to fix this and ensure backward compatibility, apart from adding the checksum to the Station model which would result in the same checksum field being duplicated for every station.

I know that the pydora API does not aim to implement **every** available Pandora function, but the ability to cache the station list does seem like a worthwhile optimisation to consider.

**Comment by mcrute** [comment]
It probably makes sense to store the checksum in the API client itself instead of on the station models.

I'm considering a `CacheAwareAPIClient` class that overloads `get_station_list` to implement the caching behind the scenes such that on the first request to `user.getStationList` the checksum will be cached on the API client and on subsequent calls will be compared to the result of `user.getStationListChecksum if the checksum changes `user.getStationList` will be called again, otherwise a cached version of the station list will be returned.

The other option is to cache the checksum on the API client and add a `station_list_changed` property that compares the cached checksum to the result of `user.getStationListChecksum` and force the API consumer to implement their own caching.

Which do you think makes the most sense for your case? I'm leaning towards the first option because it makes it easier for the API consumer.

**Comment by jcass77** [comment]
Maybe another example will be useful in coming up with the best approach:  we had a situation on the mopidy-pandora project where we needed to be able to keep the client authenticated against Pandora for long periods of time. @rectalogic wrote a really cool wrapper for ```APIClient``` using decorators to handle this use case: https://github.com/rectalogic/mopidy-pandora/blob/af7d5914100ddd28a3340c459cdbef1ebf547b8f/mopidy_pandora/pydora.py. So the more important thing there was that ```APIClient``` exposed the relevant parts of the Pandora API without having to do the low level ```APITransport``` calls ourselves.

My suggestion would be to focus on getting ```APIClient``` to parity with the Pandora API (in this case by (1) adding a ```get_station_list_checksum()``` method and (2) the ```station_list_changed``` property) and then have any other clients like ```CacheAwareAPIClient``` and ```AlwaysOnAPIClient``` (which would be nice to have available) make use of that.

I suspect that the ideal design would allow API consumers to be able to implement any type of client that they want, relying only on what ```APIClient``` provides.

**Comment by mcrute** [comment]
Okay. I'll get a version of this working this weekend. I think it's going to require breaking backwards compatibility with the current `get_station_list` API as I'll need to introduce a model there to hold the checksum. I'll make sure that the return value is iterable so you shouldn't have to do too much extra work to port to it.

I'm also going to take this time to wrap the rest of the API return values in models so it stops leaking raw JSON data.

This will also probably mark the 1.0 release since the library is pretty stable at this point.

**Comment by mcrute** [comment]
This is live now in 1.0.0. I was able to make the change in a backwards compatible way. Calls to `get_station_list` will return a list subclass that contains the stations. The model also has a  `checksum` field and the `APIClient` has a `get_station_list_checksum`. For convenience there is a `has_changed` method on the `StationList` model that will make the API call and compare the results, returning a boolean.
