### ISSUE TITLE
I Need Help

### ISSUE THREAD

**Issue by FireController1847** [mcrute/pydora#54]
I don't actually use this product, I have a question about the Unofficial Pandora API. Before you click away, it's super quick, I promise.

Alright, to the issue. I am able to get the partner login stuff fine (ex. the token, syncTime (before decode), etc). Then, I'm also able to decode the syncTime stuff aswell, getting the synccode number. But, this is where my issue comes in. I put everything together (username, pass, auth token, sync time, and putting partner_id into the url), using the method auth.userLogin, and ALWAYS; EVERY SINGLE DAMN TIME, I get a 1010 error (PARTNER_NOT_AUTHORIZED). Please, PLEASE help, I really want to get this working but it's just not workin' out.

By the way, I'm using Postman to send my requests before I get into any library, so it's simple stuff.

... and I don't have Pandora One, so internal-tuner won't be working out.

Example of my failures:
![](https://img.visualfiredev.com/dw0dq.png)

**Comment by mcrute** [comment]
I'd very strongly recommend against building yet another API unless you've got a really good reason to do so (adding a new language is the only good reason, in my opinion). I do accept pull requests for this library if there's a feature you're missing so feel free to contribute. The low level transport is purposely complicated and can be quite error prone. You'd be better served focusing on whatever your high-level goal is using [one of the existing APIs](https://6xq.net/pandora-apidoc/json/implementations/) rather than building your own. Furthermore, this isn't a forum for general API debugging as this project is dedicated specifically to the Python API Pydora. All that being said...

Based on your screenshot it looks like you're not blowfish encrypting the request body. The only API method that can be sent without encrypting the entire request body is `partnerLogin` (see the [APITransport](https://github.com/mcrute/pydora/blob/master/pandora/transport.py#L102-L236) for more details. Also, the only keys that can be used against the `internal-tuner` endpoint are the AIR and Windows Gadget keys, all others will be rejected. Finally, only Pandora One accounts can login to the `internal-tuner` endpoint. Instead you will need to use the [tuner](https://github.com/mcrute/pydora/blob/master/pandora/transport.py#L23) endpoint for all of your requests. Fixing the combination of those issues should solve your problem.

Going to close this ticket since it's off-topic. Feel free to email me directly if you want help with the API (mike at crute dot us). Otherwise, pull requests welcomed.

**Comment by FireController1847** [comment]
@mcrute Awesome, thanks. I am actually looking at making a Node.js (NPM) API, so that's why I've been asking.

**Comment by FireController1847** [comment]
Here's an invite to that server I was talking about. https://discord.gg/VqzGTV8

**Comment by mcrute** [comment]
Best of luck! Feel free to ping me over email or IRC if you have any other API questions (I don't use proprietary communications platforms). I've tried to keep the Python implementation fairly clean and easy to read so that may be illustrative as you push forward with a Node port.

**Comment by FireController1847** [comment]
@mcrute Ah, well, best of luck to you too. We'd love to have you in the server, it'd be a great addition. 👋

**Comment by FireController1847** [comment]
@mcrute Were you the one I was emailing before? If so, I seem to have lost your email. If you were, I need some help again :( Email me at usfirepilot123@gmail.com
