### ISSUE TITLE
Add docs and examples

### ISSUE THREAD

**Issue by dannkunt** [mcrute/pydora#65]
**What would you like to be added**:
Easy to understand documentation and code examples

**Why is this needed**:
Because I and 2 pepole I asked cant understand this docs.
We can't even understand how to connect to API.

Goog docs examle [PyTelegramBotApi](https://github.com/eternnoir/pyTelegramBotAPI)

**Comment by mcrute** [comment]
Pydora is just a python wrapper around the Pandora JSON v5 API, which is mostly [documented](https://6xq.net/pandora-apidoc/json/). I had intended the [pydora](https://github.com/mcrute/pydora/tree/master/pydora) package to be a little example of how to use the library. Specifically [PlayerApp](https://github.com/mcrute/pydora/blob/master/pydora/player.py#L49) is wirth a read.

I'll keep this open as a to-do to add more docs. But to get you started here's an overview:

The [APIClient](https://github.com/mcrute/pydora/blob/master/pandora/client.py#L108) is how you talk to the Pandora API. It needs some configuration and other stuff, you can make these yourself, but the easiest way is to use a [client builder](https://github.com/mcrute/pydora/blob/master/pandora/clientbuilder.py) of which the most straightforward to use is [SettingsDict](https://github.com/mcrute/pydora/blob/master/pandora/clientbuilder.py#L122) which just takes a bit of configuration and returns the configured `APIClient`. Once you have that you need to call the `login` method with the user's credentials and you're ready to go.

The `APIClient` methods all return [Python models](https://github.com/mcrute/pydora/tree/master/pandora/models) that map pretty much directly to the underlying responses from Pandora. Some models have a little bit of glue to do things like parse dates into python `datetime` objects and to call other `APIClient` methods (for example: a `PlaylistItem` can add [thumbs up](https://github.com/mcrute/pydora/blob/master/pandora/models/playlist.py#L178) and down feedback for the track).

So with all that being said, here's a super minimal worked example to load a track (you'll need to pass the track URL, which points to an mp3 or aac file, off to something that can play it, like VLC; this API doesn't actually handle turning audio data into sounds):

```python
from pandora.clientbuilder import SettingsDictBuilder

def play_music(url):
    # You'll need to implement this to do something like call VLC with the track to play it
    pass

# You will need to read the README, it has a link to a page that contains the values
# required for the below dictionary. You can copy/paste them to replace see_link_above
client = SettingsDictBuilder({
    "DECRYPTION_KEY": "see_link_above",
    "ENCRYPTION_KEY": "see_link_above",
    "PARTNER_USER": "see_link_above",
    "PARTNER_PASSWORD": "see_link_above",
    "DEVICE": "see_link_above",
}).build()

client.login("your-pandora-username", "your-pandora-password")

stations = client.get_station_list()
first_station_playlist = stations[0].get_playlist()
first_track = first_station_playlist[0]

print(f"Now playing {first_track.song_name} by {first_track.artist_name} on album {first_track.album_name}")

play_music(first_track.audio_url)
```

So that's the most simple application you can build with Pydora but you really should read the code over in the [pydora player app](https://github.com/mcrute/pydora/tree/master/pydora) since it uses a lot of the Pandora playback API and builds out a command-line player. There are also examples of how to control an audio output sync like [VLC](https://github.com/mcrute/pydora/blob/master/pydora/audio_backend.py#L246).

Until I have time for more docs, feel free to ask questions here.

**Comment by dannkunt** [comment]
1. Do you know something about "music.getTrack", it is bot in library and there is no description on rest api docs.
2. How to get more accurate search results via client.search?

**Comment by mcrute** [comment]
>     1. Do you know something about "music.getTrack", it is not in library and there is no description on rest api docs.

I don't know what that API is or what it does. How did you find out about it? Why do you think you need to use it?

Not all of the API has been discovered. The calls in the documentation are what the players up to this point have needed. In the past when I've discovered new APIs or gained a better understanding of them I submitted pull requests to [the docs](https://github.com/promyloph/pandora-apidoc/) and implemented the API call in Pydora. The maintainer of that repo is pretty responsive.

>     2. How to get more accurate search results via client.search?

As far as I know this is completely under the control of Pandora's server side code. There's nothing in the client you can do for better search results. Do you have reason to believe that the search results from Pydora are not the same as the ones returned from the official apps?
