### ISSUE TITLE
Help understand ads in Pandora and Login timeout (refresh)

### ISSUE THREAD

**Issue by ksaye** [mcrute/pydora#67]
Great library and pretty simple to implement.  Keep up the good work!

I don't fully understand Ads.  I notice in the [Player](https://github.com/mcrute/pydora/blob/master/pydora/player.py#L127), it refers to the add and play the URL, which can be something like: https://delivery-cdn-cf.adswizz.com/pandora_newEnco/ad_1440058_81641ca0358a9d681d2336475fa877a0_16077118186781147730659739.mp4?t=1

I don't see how just playing that URL counts as 'viewing' the ad.

Consider the following code:

```
from pandora.clientbuilder import SettingsDictBuilder
import subprocess
import time
from urllib.request import urlretrieve

client = SettingsDictBuilder({
    "DECRYPTION_KEY": "R=**B#",    "ENCRYPTION_KEY": "6#**WD",    "PARTNER_USER": "an**d", "PARTNER_PASSWORD": "AC**7",    "DEVICE": "and**ic",
}).build()

client.login(userName, passWord)
stations = client.get_station_list()
for station in stations:
    for play in station.get_playlist():
        if play.is_ad:
            urlretrieve(play.audio_url, 'file.mp3')
            #AdItem(audio_url='https://delivery-cdn-cf.adswizz.com/pandora_newEnco/ad_1474375_81641ca0358a9d681d2336475fa877a0_160795114776332122456604.mp4?t=1', click_through_url='', company_name='', image_url='https://cont-1.p-cdn.us/images/public/devicead/e/l/i/t/daarv2audioprogtile_500W_500H.jpg', title='', tracking_tokens=['ADU-572971547-42-232-pod/1/2/65--0-1608417888448', 'ADU-572971547-42-232-pod/1/2/65--1-1608417888449', 'ADU-572971547-42-232-pod/1/2/65--2-1608417888449', 'ADU-572971547-42-232-pod/1/2/65--3-1608417888449'])
        else:
           urlretrieve(play.audio_url, 'file.mp3')

        runCommand = str('cvlc --play-and-exit file.mp3').split()
        playSongProcess = subprocess.Popen(runCommand, stdin=subprocess.PIPE, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, encoding="utf-8")
        while playSongProcess.poll() == None:
            time.sleep(1)  # still running 
 ```
Any insight on ads?

Also, I think Pandora times out the login.  Should I ```client.login()``` periodically or how can I trap a need to login again?

**Comment by mcrute** [comment]
> Any insight on ads?

To log the ad impression you need to call [`AdItem.register_ad`](https://github.com/mcrute/pydora/blob/master/pandora/models/ad.py#L21) which sends the appropriate ping to Pandora. You should do this before you play the ad audio file. Also in the spirit of playing nicely with Pandora's API, you should not allow users to skip ads.

The Pydora player does this in [`utils.iterate_forever`](https://github.com/mcrute/pydora/blob/master/pydora/utils.py#L190) by calling the [`PlaylistModel.prepare_playback`](https://github.com/mcrute/pydora/blob/master/pandora/models/ad.py#L31) method which makes the correct `register_ad` call. The superclass [`prepare_playback`](https://github.com/mcrute/pydora/blob/master/pandora/models/playlist.py#L114) is simply a no-op so it's safe to assume you can always call this before playing.

> Also, I think Pandora times out the login. Should I `client.login()` periodically or how can I trap a need to login again?

I haven't encountered this in any of my uses, nor have I had any other consumers report this being an issue. If you have the time to dig into it and a file a more detailed bug report I'd much appreciate it. Otherwise I'd guess you'll see a [`Invalid Auth Token`](https://github.com/mcrute/pydora/blob/master/pandora/errors.py#L32) error or something similar when calling API methods that you can catch and re-try the login.

Going to close this issue since that should answer your questions. Feel free to re-open if there's anything else.

**Comment by mcrute** [comment]
I just noticed that it looks like you're trying to drive VLC as well... you might find [`pydora.audio_backend.VLCPlayer`](https://github.com/mcrute/pydora/blob/master/pydora/audio_backend.py#L246) useful. It's not part of the `pandora` package and doesn't enjoy any of the API stability guarantees of that package but in practice it hasn't changed too terribly much since I wrote it and it handles all the tricky bits of driving VLC either locally or remotely.
